---
- hosts: all
  become: true
  tasks:
  - name: install nginx 
  yum:
  name: ngnix
  state: latest
  -name: copy index.html
  copy:
  src: index.html 
  dest: /var/www/html/index.html mode
- name: start nginx service
  service:
   name: nginx
   state: started
...

  